packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  dev:
    '@babel/core': ^7.28.3
    '@pixpilot/dev-config': ^3.1.2
    '@types/jest': ^30.0.0
    '@types/node': ^24.9.0
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    autoprefixer: ^10.4.21
    eslint: ^9.34.0
    jest: ^30.0.5
    postcss: ^8.5.6
    prettier: ^3.6.2
    ts-jest: ^29.4.1
    typescript: ^5.9.2
    typescript-eslint: ^8.40.0
    vitest: ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    tailwindcss: 4.1.12

  prod:
    react: 19.0.0
    react-dom: 19.0.0
    zod: 4.0.17
